#!/bin/sh

# Utility script to run the RMI frontend on the specified arguments.

if [ -z "$RMI_HOME" ];  then
    echo "please set RMI_HOME to the location of your RMI installation" 1>&2
    exit 1
fi

# Note: this requires Java 6
exec java \
    -classpath "$CLASSPATH:$RMI_HOME/lib/"'*' \
    -Dlog4j.configuration=file:$RMI_HOME/log4j.properties \
    ibis.compile.Ibisc \
    -rmi -rmi-java2ibis "$@"
